"""Update Session table

Revision ID: f86990301e3b
Revises: 
Create Date: 2025-10-05 15:09:03.869674

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'f86990301e3b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['url'])
        batch_op.create_foreign_key(
            "fk_opportunity_user_id",  # <- name
                "user", 
                ["user_id"], 
                ["id"]
        )
        batch_op.drop_column('three_matched_scores_and_recommended_partners_ids')

    with op.batch_alter_table('partner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('linkedin_url', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('linkedin_data', postgresql.JSON(astext_type=Text()), nullable=True))
        batch_op.drop_column('linkedindata')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('linkedindata', sqlite.JSON(), nullable=True))
        batch_op.drop_column('linkedin_data')
        batch_op.drop_column('linkedin_url')

    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('three_matched_scores_and_recommended_partners_ids', sa.TEXT(), nullable=True))
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
